const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const request = require('supertest');
let db, app, database, socket;
const password = 'Test-only-password-2026';
let alice, bob, pa, pb, ua, ub;
before(async () => {
  process.env.NODE_ENV = 'test';
  if (!process.env.TEST_DATABASE_URL) {
    const { PGlite } = await import('@electric-sql/pglite');
    const { PGLiteSocketServer } = await import('@electric-sql/pglite-socket');
    database = await PGlite.create();
    socket = new PGLiteSocketServer({ db: database, port: 5439, host: '127.0.0.1' });
    await socket.start();
    process.env.DATABASE_URL = 'postgresql://postgres:postgres@127.0.0.1:5439/postgres';
    process.env.DATABASE_POOL_MAX = '1';
  } else process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
  process.env.CREDENTIAL_ENCRYPTION_KEY = 'ab'.repeat(32);
  db = require('../src/db');
  await db.migrate.latest();
  app = require('../server');
  alice = request.agent(app); bob = request.agent(app);
}, { timeout: 120000 });
after(async () => { if (db) await db.destroy(); if(socket)await socket.stop(); if(database)await database.close(); });
const account = id => ({ username: `owner-${id}`, name: `Owner ${id}`, email: `${id}@example.test`, password });
const property = id => ({ property_id: `property-${id}`, name: `Property ${id}`, city: 'Thika', contact_phone: '0712345678' });
test('atomic self onboarding creates a property owner and HttpOnly session', async () => {
  const r = await alice.post('/api/admin/onboard').send({ account: account('a'), property: property('a') });
  assert.equal(r.status, 201, JSON.stringify(r.body)); pa = r.body.property;
  assert.equal(r.body.user.role, 'property_admin'); assert.equal(r.body.user.properties[0].is_owner, true);
  assert.match(r.headers['set-cookie'][0], /HttpOnly/); assert.match(r.headers['set-cookie'][0], /SameSite=Strict/); assert.equal(r.body.token, undefined);
  const b = await bob.post('/api/admin/onboard').send({ account: account('b'), property: property('b') });
  assert.equal(b.status, 201, JSON.stringify(b.body)); pb = b.body.property;
  const duplicate = await request(app).post('/api/admin/onboard').send({ account: account('c'), property: property('a') });
  assert.equal(duplicate.status, 409); assert.equal(await db('admin_users').where('username','owner-c').first(), undefined);
});
test('properties, units and writes are isolated across owners', async () => {
  const listed = await alice.get('/api/admin/properties'); assert.equal(listed.body.data.length, 1);
  assert.equal(listed.body.data[0].id, pa.id);
  const makeUnit = (p, id) => ({ property_id: p.property_id, unit_id:id, name:'Garden suite', type:'bnb', bedrooms:1,bathrooms:1,base_price_kes:3000,max_guests:6 });
  const r = await alice.post('/api/admin/units').send(makeUnit(pa,'garden-a')); assert.equal(r.status,201,JSON.stringify(r.body)); ua=r.body.data;
  const s = await bob.post('/api/admin/units').send(makeUnit(pb,'garden-b')); assert.equal(s.status,201,JSON.stringify(s.body)); ub=s.body.data;
  assert.equal((await alice.get('/api/admin/units')).body.data.length,1);
  assert.equal((await alice.put(`/api/admin/units/${ub.id}`).send({name:'Intrusion'})).status,403);
  assert.equal((await alice.post('/api/admin/units').send(makeUnit(pb,'intrusion'))).status,403);
  assert.equal((await alice.get('/api/admin/units').set('X-Property-ID',pb.property_id)).status,403);
  assert.equal((await alice.get('/api/admin/admins')).status,403);
  await alice.put(`/api/admin/units/${ua.id}`).send({max_guests:6,extra_guest_charge:0,description:'Keep this description',status:'maintenance'});
  const patched=await alice.put(`/api/admin/units/${ua.id}`).send({name:'Renamed suite'});
  assert.equal(patched.body.data.description,'Keep this description');assert.equal(patched.body.data.max_guests,6);assert.equal(patched.body.data.extra_guest_charge,0);assert.equal(patched.body.data.status,'maintenance');
  await alice.put(`/api/admin/units/${ua.id}`).send({status:'active'});
});
test('draft, publish, revision conflict and unpublish work without exposing drafts',async()=>{
  assert.equal((await request(app).get('/api/websites/'+pa.property_id)).status,404);
  const content={ name:'Garden House', description:'A quiet place in Thika.', contact_phone:'0712345678',hero_image_url:'https://images.example.test/house.jpg',features:['Parking'] };
  const save=await alice.put(`/api/admin/properties/${pa.id}/website`).send({content,version:1}); assert.equal(save.status,200,JSON.stringify(save.body));
  assert.equal((await alice.put(`/api/admin/properties/${pa.id}/website`).send({content,version:1})).status,409);
  assert.equal((await bob.get(`/api/admin/properties/${pa.id}/website`)).status,403);
  const publish=await alice.post(`/api/admin/properties/${pa.id}/website/publish`).send({version:2}); assert.equal(publish.status,200,JSON.stringify(publish.body));
  const live=await request(app).get('/api/websites/'+pa.property_id);assert.equal(live.body.data.name,'Garden House');assert.equal(live.body.units.length,1);
  await alice.put(`/api/admin/properties/${pa.id}/website`).send({content:{...content,name:'Not published yet'},version:3});
  assert.equal((await request(app).get('/api/websites/'+pa.property_id)).body.data.name,'Garden House');
  const unsafe=await alice.put(`/api/admin/properties/${pa.id}/website`).send({content:{...content,hero_image_url:'javascript:alert(1)'},version:4});assert.equal(unsafe.status,400);
});
test('bookings require auth and cannot overlap or cross properties',async()=>{
  assert.equal((await request(app).get('/api/bookings')).status,401);
  assert.equal((await request(app).post('/api/bookings').send({})).status,401);
  const body={unitId:ua.id,guestName:'Guest',guestPhone:'0712345678',checkinDate:'2027-02-10',checkoutDate:'2027-02-12',guests:2,totalKes:1};
  const r=await alice.post('/api/admin/bookings').send(body);assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.data.total_amount_kes,6000);
  assert.equal((await bob.get('/api/bookings/'+r.body.id)).status,403);
  assert.equal((await alice.post('/api/admin/bookings').send(body)).status,409);
  const rules=await alice.post('/api/admin/pricing-rules').send({unitId:ua.unit_id,startDate:'2027-03-01',endDate:'2027-03-02',pricePerNightKes:5000});assert.equal(rules.status,201,JSON.stringify(rules.body));
  const quote=await request(app).post('/api/calendar/check-availability').send({unitId:ua.unit_id,checkinDate:'2027-03-01',checkoutDate:'2027-03-03',totalGuests:2});assert.equal(quote.body.data.pricing.finalPrice,8000);
  const calendar=await request(app).get(`/api/calendar/availability/${ua.unit_id}?startDate=2027-02-01&endDate=2027-03-01`);assert.equal(calendar.status,200);assert.equal(calendar.body.data.calendar.bookedDates[0].guestName,undefined);
});
test('disabled accounts and revoked memberships take effect immediately',async()=>{
  const user=await db('admin_users').where('username','owner-b').first();
  await db('admin_users').where('id',user.id).update({status:'inactive'});
  assert.equal((await bob.get('/api/admin/properties')).status,401);
  await db('admin_users').where('id',user.id).update({status:'active'});
  await db('admin_properties').where('admin_id',user.id).delete();
  assert.equal((await bob.get('/api/admin/properties')).body.data.length,0);
  assert.equal((await bob.put('/api/admin/units/'+ub.id).send({name:'Removed member'})).status,403);
});
test('same-origin protection, bounded bodies, and private payment status',async()=>{
  assert.equal((await alice.post('/api/admin/properties').set('Origin','https://evil.example').send(property('x'))).status,403);
  assert.equal((await request(app).post('/api/mpesa/callback').send({})).status,404);
  assert.equal((await request(app).get('/api/mpesa/bookings')).status,401);
  assert.equal((await request(app).get('/api/mpesa/status/'+crypto.randomUUID())).status,400);
  const r=await request(app).post('/api/admin/login').send({username:'owner-a',password:'wrong'});assert.equal(r.status,401);assert.equal(JSON.stringify(r.body).includes('password_hash'),false);
});
test('team invitations bind email, cannot grant ownership, and cannot be replayed', async()=>{
  const invited=await alice.post(`/api/admin/properties/${pa.id}/team`).send({email:'manager@example.test'});
  assert.equal(invited.status,201,JSON.stringify(invited.body));
  const token=invited.body.path.split('invite=')[1];
  const manager=request.agent(app);
  const wrong=await manager.post('/api/admin/accept-invite').send({token,account:account('wrong')});assert.equal(wrong.status,400);
  const accepted=await manager.post('/api/admin/accept-invite').send({token,account:{...account('manager'),email:'manager@example.test'}});assert.equal(accepted.status,200,JSON.stringify(accepted.body));
  assert.equal(accepted.body.user.properties[0].is_owner,false);
  assert.equal((await manager.get(`/api/admin/properties/${pa.id}/website`)).status,200);
  assert.equal((await manager.get(`/api/admin/properties/${pa.id}/team`)).status,403);
  assert.equal((await manager.get(`/api/admin/properties/${pa.id}/payments-settings`)).status,403);
  assert.equal((await manager.post('/api/admin/invitations/accept').send({token})).status,400);
  await alice.delete(`/api/admin/properties/${pa.id}/team/${accepted.body.user.id}`);
  assert.equal((await manager.get(`/api/admin/properties/${pa.id}/website`)).status,403);
});
test('rental contracts and payment ledger enforce property relationships and retry safety',async()=>{
  const unit=await alice.post('/api/admin/units').send({property_id:pa.property_id,unit_id:'long-stay',name:'Studio',type:'bedsit',bedrooms:0,bathrooms:1,base_price_kes:12000});assert.equal(unit.status,201,JSON.stringify(unit.body));
  const t=await alice.post('/api/admin/tenants').send({property_id:pa.property_id,tenant_name:'Tenant',tenant_phone:'0712345678'});assert.equal(t.status,201,JSON.stringify(t.body));
  const terms={tenant_id:t.body.data.id,unit_id:unit.body.data.id,property_id:pa.property_id,start_date:'2026-08-15',monthly_rent_kes:12000,security_deposit_kes:12000,utilities_deposit_kes:1000};
  assert.equal((await alice.post('/api/admin/contracts').send({...terms,property_id:pb.property_id})).status,400);
  const lease=await alice.post('/api/admin/contracts').send(terms);assert.equal(lease.status,201,JSON.stringify(lease.body));
  assert.equal((await alice.post('/api/admin/contracts').send(terms)).status,409);
  assert.equal((await alice.put('/api/admin/contracts/'+lease.body.data.id).send({monthly_rent_kes:1})).status,409);
  const pay={contract_id:lease.body.data.id,tenant_id:t.body.data.id,unit_id:unit.body.data.id,month:8,year:2026,amount_paid_kes:5000,idempotency_key:crypto.randomUUID()};
  assert.equal((await alice.post('/api/admin/payments').send({...pay,unit_id:ub.id})).status,400);
  const [one,two]=await Promise.all([alice.post('/api/admin/payments').send(pay),alice.post('/api/admin/payments').send(pay)]);
  assert.equal(one.status,201,JSON.stringify(one.body));assert.equal(two.status,201,JSON.stringify(two.body));assert.equal(two.body.data.amount_paid_kes,5000);
  assert.equal((await alice.post('/api/admin/payments').send({...pay,amount_paid_kes:6000})).status,409);
  const remainder=await alice.post('/api/admin/payments').send({...pay,amount_paid_kes:7000,idempotency_key:crypto.randomUUID()});assert.equal(remainder.body.data.amount_outstanding_kes,0);
  const arrears=await alice.get(`/api/admin/tenants/${t.body.data.id}/arrears`);assert.equal(arrears.status,200,JSON.stringify(arrears.body));
  const dashboard=await alice.get('/api/admin/dashboard');assert.equal(dashboard.status,200,JSON.stringify(dashboard.body));assert.equal(dashboard.body.data.rentReceived,12000);assert.equal(dashboard.body.data.activeLeases,1);
  assert.equal((await alice.delete(`/api/admin/tenants/${t.body.data.id}`)).status,409);
});
test('M-Pesa uses server prices, isolated encrypted credentials, durable callbacks and idempotent reconciliation',async()=>{
  const merchant=require('../src/merchantService');const original=merchant.client;let sends=0;let queryCode=0;
  merchant.client=()=>({stkPush:async()=>({ResponseCode:'0',CheckoutRequestID:'checkout-'+(++sends),MerchantRequestID:'merchant-'+sends}),stkQuery:async()=>({ResultCode:queryCode})});
  process.env.SITE_ORIGIN='https://properties.example.test';
  try{
    const settings={enabled:true,environment:'sandbox',shortcode:'174379',transaction_type:'CustomerPayBillOnline',consumer_key:'test-key',consumer_secret:'test-secret',passkey:'test-passkey'};
    const saved=await alice.put(`/api/admin/properties/${pa.id}/payments-settings`).send(settings);assert.equal(saved.status,200,JSON.stringify(saved.body));
    const exposed=await alice.get(`/api/admin/properties/${pa.id}/payments-settings`);assert.equal(exposed.body.data.consumer_secret,undefined);
    const stored=await db('property_merchant_settings').where('property_id',pa.id).first();assert.equal(stored.credentials_encrypted.includes('test-secret'),false);
    const key=crypto.randomUUID(),body={unitId:ua.unit_id,property:pa.property_id,type:'bnb',guestName:'Paying guest',guestPhone:'0712345678',phone:'0712345678',checkin:'2027-05-01',checkout:'2027-05-03',guests:2};
    assert.equal((await request(app).post('/api/mpesa/stk-push').set('Idempotency-Key',key).send({...body,amount:1})).status,409);assert.equal(sends,0);
    const first=await request(app).post('/api/mpesa/stk-push').set('Idempotency-Key',key).send(body);assert.equal(first.status,200,JSON.stringify(first.body));assert.equal(first.body.amount,6000);
    const retry=await request(app).post('/api/mpesa/stk-push').set('Idempotency-Key',key).send(body);assert.equal(retry.body.bookingId,first.body.bookingId);assert.equal(sends,1);
    assert.equal((await request(app).get('/api/mpesa/status/'+first.body.bookingId).set('X-Booking-Token',crypto.randomUUID())).status,404);
    const callback=(amount,receipt='TESTRECEIPT1')=>({Body:{stkCallback:{CheckoutRequestID:'checkout-'+sends,MerchantRequestID:'merchant-'+sends,ResultCode:0,CallbackMetadata:{Item:[{Name:'Amount',Value:amount},{Name:'PhoneNumber',Value:254712345678},{Name:'MpesaReceiptNumber',Value:receipt}]}}}});
    assert.equal((await request(app).post('/api/mpesa/callback/'+'0'.repeat(64)).send(callback(6000))).status,404);
    assert.equal((await request(app).post('/api/mpesa/callback/'+stored.callback_token).send(callback(6000))).status,200);
    assert.equal((await db('bookings').where('id',first.body.bookingId).first()).status,'pending');
    const mpesa=require('../src/mpesaRoutes');await mpesa.runMaintenance();await mpesa.runMaintenance();
    assert.equal((await db('bookings').where('id',first.body.bookingId).first()).status,'confirmed');
    const rental=await alice.post('/api/admin/units').send({property_id:pa.property_id,unit_id:'deposit-studio',name:'Deposit studio',type:'bedsit',bedrooms:0,bathrooms:1,base_price_kes:10000,water_deposit_kes:1500});assert.equal(rental.status,201);
    const rent=await request(app).post('/api/mpesa/stk-push').set('Idempotency-Key',crypto.randomUUID()).send({...body,unitId:rental.body.data.unit_id,type:'rental'});assert.equal(rent.status,200,JSON.stringify(rent.body));assert.equal(rent.body.amount,21500);
    await request(app).post('/api/mpesa/callback/'+stored.callback_token).send(callback(21500,'TESTRECEIPT2'));
    await mpesa.runMaintenance();await mpesa.runMaintenance();
    const deposit=await db('rental_deposits').where('id',rent.body.bookingId).first();assert.equal(deposit.status,'confirmed');
    const contract=await db('rental_contracts').where('id',deposit.contract_id).first();assert.equal(contract.security_deposit_kes,10000);assert.equal(contract.utilities_deposit_kes,1500);
    const payment=await db('rental_payments').where('contract_id',contract.id);assert.equal(payment.length,1);assert.equal(payment[0].amount_paid_kes,10000);
    const mismatch=await request(app).post('/api/mpesa/stk-push').set('Idempotency-Key',crypto.randomUUID()).send({...body,checkin:'2027-06-01',checkout:'2027-06-03'});assert.equal(mismatch.status,200);
    await request(app).post('/api/mpesa/callback/'+stored.callback_token).send(callback(1,'TESTRECEIPT3'));await mpesa.runMaintenance();
    const review=await db('payment_attempts').where('record_id',mismatch.body.bookingId).first();assert.equal(review.status,'needs_review');
    assert.equal((await db('bookings').where('id',mismatch.body.bookingId).first()).status,'pending');
  }finally{merchant.client=original;delete process.env.SITE_ORIGIN;}
});
test('unpublishing removes the property and its units from all public entry points',async()=>{
  const site=(await alice.get(`/api/admin/properties/${pa.id}/website`)).body.data;
  const result=await alice.post(`/api/admin/properties/${pa.id}/website/unpublish`).send({version:site.version});assert.equal(result.status,200);
  for(const path of [`/p/${pa.property_id}`,`/api/websites/${pa.property_id}`,`/api/calendar/pricing/${ua.unit_id}`]) assert.equal((await request(app).get(path)).status,404,path);
  const units=await request(app).get('/api/calendar/units');assert.equal(units.body.data.length,0);
});
